#!/bin/bash
set -eu

CONSUL_HOST="${CONSUL_HOST:-localhost}"
CONSUL_PORT="${CONSUL_PORT:-8500}"

CONSUL_ADDR="http://${CONSUL_HOST}:${CONSUL_PORT}"

usage() {
    echo "Usage:"
    echo "  ${0##*/} <task id> [--period=<seconds>] <command>..."
    exit 1
}

grab_lock_or_die() {
    local task_id="$1"
    local current_run="$2"
    local period="$3"
    local query="${CONSUL_ADDR}/v1/kv/cronsul/${task_id}/${period}"

    json="$(curl -sS -X GET "${query}")"
    if [[ "$json" != "" ]]; then
        local last_run="$(grep -Po '"Value":.*?[^\\]",' <<< ${json} | awk -F\" '{print $4}' | base64 --decode)"
        local modify_index="$(grep -Po '"ModifyIndex":[\0-9]*' <<< ${json} | awk -F\: '{print $2}')"
    fi

    # Check if this ran already some other machine.
    if [[ "${last_run:-0}" -ge "$((current_run-$period))" ]]; then
        exit 0
    fi

    ret="$(curl -sS -X PUT -d "${current_run}" "${query}?cas=${modify_index:-0}")"
    if [[ "$ret" != "true" ]]; then
        if [[ "$ret" != "false" ]]; then
             echo $ret
        fi
        exit 1
    fi
}

# Parse command line arguments.
if [[ "$#" -lt 2 ]]; then
    usage
fi
task_id="$1"
shift
case "$1" in
    --period) period="$2"; shift 2;;
    --period=*) period="${1##--period=}"; shift;;
    *) period=60;
esac

command=("$@")

current_run="$(date '+%s')"

grab_lock_or_die "$task_id" "$current_run" "$period"

"${command[@]}"
